server:
  port: 8080

spring:
  application:
    name: acquire-india
  
  datasource:
    url: jdbc:mysql://localhost:3306/acquire_india?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:your-email@gmail.com}
    password: ${EMAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: 86400000 # 24 hours

razorpay:
  key-id: ${RAZORPAY_KEY_ID:your-razorpay-key}
  key-secret: ${RAZORPAY_KEY_SECRET:your-razorpay-secret}

file:
  upload-dir: uploads/

logging:
  level:
    com.acquireindia: DEBUG